### ISSUE TITLE
Process manifest

### ISSUE THREAD

**Issue by odinuv** [keboola/processor-headers#1]
- when modyfing columns, file manifest has to be modified too
- for backward compat. manifest may or may not be present

**Comment by ondrejhlavacek** [comment]
hm, hm, hm, hm, hm

Přemejšlim, jak na sebe napojit `processor-create-manifest` a `processor-orthogonal-csv`. 

Chtěl bych říct, že `processor-orthogonal-csv` nemá na vstupu nic a že si parametry CSV přečte z manifestu. 

Takže by konfigurace musela bejt takováhle

```
{
    "processors": {
        "after": [
            {
                "definition": {
                    "component": "keboola.processor-create-manifest"
                },
                "parameters": {
                    "delimiter": "\t",
                    "enclosure": "'"
                }
            },
            {
                "definition": {
                    "component": "keboola.processor-orthogonal-csv"
                }
            },
            {
                "definition": {
                    "component": "keboola.processor-create-manifest"
                },
                "parameters": {
                    "columns_from": "header"
                }
            }
        ]
    }
}
```

Přijde mi to zamotaný, ale dává to smysl.

**Comment by ondrejhlavacek** [comment]
+ podpora pro slicovaný soubory

**Comment by odinuv** [comment]
to je divny, proc by tam mel byt 2x create-manifest? orthogonal by mel predpokladat, ze manifest existuje a upravit ho kdyz pridava sloupce, ne?

**Comment by odinuv** [comment]
naopak bych mozna aji rekl, ze by create manifest mel failnout kdyz manifest uz existuje

**Comment by ondrejhlavacek** [comment]
mějme CSV

```csv
col1,
val1
val2,val3,val4
```

jakej z toho chceš udělat manifest? 
 - `columns_from: header` udělá `["col1", ""]`
 - `columns_from: auto` udělá `["col_1", "col_2"]` a bude se muset ještě poslat `processor-skip-lines`

**Comment by ondrejhlavacek** [comment]
> naopak bych mozna aji rekl, ze by create manifest mel failnout kdyz manifest uz existuje

možná! nějak jsem si myslel, že by to mělo usnadnit práci v extraktoru, když třeba chce předat metadata ale nemusel by řešit zbytek

**Comment by ondrejhlavacek** [comment]
dohodli jsme se na tom, že `processor-orthogonal` doplní do manifestu hlavičky podle toho, jak to CSV upraví.

**Comment by odinuv** [comment]
+ by teda processor-orthogonal nemel prijimat parametry CSV souboru - delimiter,enclosure, protoze CSV bude ve standardnim formatu (da se pred to format CSV)

**Comment by odinuv** [comment]
jo, myslel jsem jako https://github.com/keboola/processor-headers/issues/1#issuecomment-343411884 CSV je potreba modifikovat a create-manifest hlavicky neporesi, protoze nevi kolik jich je - musi se precist cely CSV

**Comment by ondrejhlavacek** [comment]
No jasně, blbě jsem to napsal, modifikací jsem myslel pouze doplnění hlaviček, create manifest umí vygenerovat hlavičky, ale počet sloupců bere z prvního řádku

**Comment by odinuv** [comment]
in https://github.com/keboola/processor-orthogonal/pull/1

**Comment by odinuv** [comment]
replaced by  https://github.com/keboola/processor-orthogonal
